version: '3.8'
services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: meu_banco_de_dados
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - rede

  app:
    build: ./flask
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: usuario
      DATABASE_PASSWORD: senha
      DATABASE_NAME: meu_banco_de_dados
    ports:
      - "5000:5000"
    networks:
      - rede

networks:
  rede:
