version: '3.8'
services:
  db:
    build: ./db
    container_name: meu_banco_de_dados
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./config/var.env
    networks:
      - rede

  app:
    build: ./flask
    container_name: minha_api_flask
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./config/var.env
    networks:
      - rede

networks:
  rede:

volumes:
  postgres_data:
